name: Enforce Branch Naming Convention

on:
  create:
    branches:
      - '**' # Trigger on any branch creation

jobs:
  check-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Extract branch name
        id: extract_branch
        run: |
          echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "Extracted branch name: ${GITHUB_REF#refs/heads/}"

      - name: Validate branch name
        id: validate_branch
        run: |
          if [[ ! "${{ env.branch_name }}" =~ ^(feature|bugfix|hotfix)\/[a-zA-Z0-9_]+(-[a-zA-Z0-9]+)?$ ]]; then
            echo "Branch name '${{ env.branch_name }}' does not follow the convention: 'feature/name', 'bugfix/name', or 'hotfix/name', with optional '-suffix'"
            exit 1
          fi
        shell: bash

      - name: Configure Git for PAT Authentication
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Delete invalid branch
        if: ${{ failure() }}
        run: |
          if [ -n "${{ env.branch_name }}" ]; then
            echo "Deleting invalid branch: ${{ env.branch_name }}"
            git push origin --delete "${{ env.branch_name }}"
          else
            echo "Branch name is empty or invalid, skipping deletion."
          fi
