name: Enforce Branch Naming Convention

on:
  create:
    branches:
      - '**' # Trigger on any branch creation

jobs:
  check-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Extract branch name
        id: extract_branch
        run: echo "::set-output name=branch_name::${GITHUB_REF#refs/heads/}"

      - name: Validate branch name
        id: validate_branch
        run: |
          if [[ ! "${{ steps.extract_branch.outputs.branch_name }}" =~ ^feature\/[a-zA-Z0-9_-]+-[0-9]+$ ]]; then
            echo "Branch name does not follow the convention: feature/anyname-number"
            exit 1
          fi

      - name: Set up Git with PAT
        if: ${{ failure() }}
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Verify Authentication
        if: ${{ failure() }}
        run: git ls-remote

      - name: Delete invalid branch
        if: ${{ failure() }}
        run: git push origin --delete ${{ steps.extract_branch.outputs.branch_name }}
